"""Reports API Routes - PDF generation"""

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from database import get_db
from datetime import datetime
import io
import logging

router = APIRouter()
logger = logging.getLogger(__name__)


@router.get("/generate/{inspection_id}")
async def generate_report(inspection_id: str):
    db = get_db()
    try:
        doc = await db.inspections.find_one({"inspection_id": inspection_id})
        if not doc:
            return {"error": "Inspection not found"}
        doc.pop("_id", None)
        if isinstance(doc.get("timestamp"), datetime):
            doc["timestamp"] = doc["timestamp"].isoformat()

        # Generate simple text report (PDF library optional)
        report_text = f"""
THERMOGRAPHY COMPLIANCE AI
INSPECTION REPORT
{'='*60}

Report ID: {inspection_id}
Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
Standard: {doc.get('standard', 'NFPA 70B')}

EQUIPMENT DETAILS
{'-'*40}
Equipment: {doc.get('equipment_name', 'N/A')}
Type: {doc.get('equipment_type', 'N/A')}
Location: {doc.get('location', 'N/A')}
Inspector: {doc.get('inspector', 'N/A')}

THERMAL ANALYSIS
{'-'*40}
Ambient Temperature: {doc.get('ambient_temp', 'N/A')}°C
Hotspot Temperature: {doc.get('hotspot_temp', 'N/A')}°C
Delta-T: {doc.get('delta_t', 'N/A')}°C
Severity Classification: {doc.get('severity', 'N/A')}
Compliance Score: {doc.get('compliance_score', 'N/A')}/100

FINDINGS
{'-'*40}
{doc.get('finding', 'N/A')}

RECOMMENDATIONS
{'-'*40}
{doc.get('recommendation', 'N/A')}

STATUS: {doc.get('status', 'N/A')}

{'='*60}
This report is generated by Thermography Compliance AI.
Compliant with {doc.get('standard', 'NFPA 70B')} standards.
        """

        buf = io.BytesIO(report_text.encode())
        buf.seek(0)
        return StreamingResponse(
            buf,
            media_type="text/plain",
            headers={"Content-Disposition": f"attachment; filename=report_{inspection_id}.txt"}
        )
    except Exception as e:
        logger.error(f"Report generation error: {e}")
        return {"error": str(e)}


@router.get("/summary")
async def get_reports_summary():
    db = get_db()
    try:
        total = await db.inspections.count_documents({})
        critical = await db.inspections.count_documents({"severity": "Critical"})
        docs = await db.inspections.find({}, {"compliance_score": 1}).to_list(1000)
        scores = [d.get("compliance_score", 0) for d in docs if d.get("compliance_score")]
        avg = round(sum(scores) / len(scores), 1) if scores else 0

        return {
            "total_reports": total,
            "critical_findings": critical,
            "avg_compliance": avg,
            "reports_this_month": await db.inspections.count_documents({}),
        }
    except Exception as e:
        logger.error(f"Reports summary error: {e}")
        return {"total_reports": 0, "critical_findings": 0, "avg_compliance": 0}
